inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

require:
  - rubocop-rails

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

Style/GlobalVars:
  AllowedVariables: [$LIBS,$CFLAGS]

Lint/SuppressedException:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false